### ISSUE TITLE
Notifications not initializing properly

### ISSUE THREAD

**Issue by mekwall** [jfurrow/flood#176]
I am having this issue where I get stuck during initialization due to notifications never initializing, even though they seem to be loaded properly:

![image](https://cloud.githubusercontent.com/assets/37091/20258448/07f8d48e-aa50-11e6-97b9-9626c4e4d688.png)

The only way to get it to work is to delete `notifications.db` and restart flood.

**Comment by jfurrow** [comment]
This should be fixed by https://github.com/jfurrow/flood/pull/177, but would you mind verifying?

**Comment by jfurrow** [comment]
I'm pretty sure #177 will fix this, so I'm going to merge and close this issue. Feel free to reopen if the issue persists!

**Comment by mekwall** [comment]
Since pulling the latest code it hasn't happened so I guess it's been resolved. Thanks for the quick fix! 👍

**Comment by mekwall** [comment]
@jfurrow Seems we celebrated success a bit too early. Issue is still happening :(

**Comment by jfurrow** [comment]
@mekwall Sorry for the delay and for erroneously closing your issue. I didn't see your comment until just now. I am almost certain it's fixed by this PR: https://github.com/jfurrow/flood/pull/186. Would you be willing to verify?

Thanks, and sorry! This bug was also reported in https://github.com/jfurrow/flood/issues/184

**Comment by jfurrow** [comment]
@mekwall Another user confirmed this was fixed by https://github.com/jfurrow/flood/pull/186. Pull the latest from `master`; if this is still happening, feel free to re-open this issue.

Thanks for reporting!
